### ISSUE TITLE
About my C++20 framework, I have to post this issue here.

### ISSUE THREAD

**Issue by SpringOrHaru** [sandordargo/sandordargo.github.io#2]
Hello, 
You did not appear to check your email (found on your blog site) for a long time and see my messages about my C++20 framework.
I am glad to get you to have a discussion about it (Please check your email first).

My C++20 framework covers GUI and additionally covers a lot of other stuff to be general-purpose.
For now, I want to keep my creation hidden. This is a spark to get feedback (what my C++ code looks like, etc).

Being able to create a C++20 framework all by myself is a whole talent on its own, I want you to notice it.
Maybe you can make me have fun creating some apps which will put my C++20 framework to the test.

P.S.: I hope the fact you work for a company and the fact you are an introvert do not make you ignore all other interesting things about C++ in life.

**Comment by SpringOrHaru** [comment]
Look, your email is mentioned on your blog site and yet I still have not heard anything back from you after waiting for a couple of weeks.

You understand I am getting impatient and uncomfortable.

So much for putting my effort in announcing my C++20 framework and no one will ever bother to know (Correct me, if I am wrong).

Does it have to be this difficult to ask a programmer for feedback?

It is strange that you specialize in C++ but this topic is what you ignore or you fail to notice. I am trying to contact you.

I look forward to discussing my C++20 framework with somebody. When I have a reply, it will be an exciting start.

**Comment by sandordargo** [comment]
Hi Tianji,

I checked I only received two spam mails from you and I don't check my spams...

![image](https://user-images.githubusercontent.com/5472553/185755594-83c66a1d-0b78-4d51-84c9-6aa7442e6488.png)

But honestly, these kinds of aggressive messages don't help you. Now I feel uncomfortable.

Good bye and good luck.

**Comment by SpringOrHaru** [comment]
As a programmer, you should be contributing better in the C++ ecosystem by offering me feedback.

I am uncomfortable if waited long enough, it is natural. So more messages because you made me wait for too long.

"Good luck" is out of the question here. Sorry for me because I only picked a single person to contact. An introvert like me does not have the energy left to contact someone else.

I think sharing is caring, but introverted programmers are not kind to each other. Is that the impression I am getting?

I am sorry for my attitude, if you think I am being aggressive.
I am happy for your reply.

Now we can get to the important matter, you give me some feedback about my C++20 framework by reading my C++ code.

In case you have not received any attachments yet, **I will send them again to you via email**. Thanks.

**Comment by sandordargo** [comment]
I'm sorry, I don't intend to interact with anyone who is writing in such an aggressive and demanding style as if I owed you something. I'm blocking you.
